load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "maze",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
)
